name: "Visual Development Lab"
description: "Angueyra Lab website"

url: "http://angueyraLab.github.io"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
